### ISSUE TITLE
Terrame internal error: attempt to index local 'ev' (a number value)

### ISSUE THREAD

**Issue by brunaezleal** [TerraME/terrame#1053]
This error was shown when attempting to run the continuous-rain.lua and beer.lua exemples with:

TerraME - Terra Modeling Environment
Version: 2.0
Location (TME_PATH): C:\TerraME\bin
Compiled with:
  Lua 5.2.2
  Qt 5.5.1
  Qwt 6.1.2
  TerraLib 5.1.2

*************************************************************
UNEXPECTED TERRAME INTERNAL ERROR. PLEASE GIVE US A FEEDBACK.
WRITE AN EMAIL TO pedro.andrade@inpe.br REPORTING THIS ERROR.
*************************************************************
C:\TerraME\bin\packages\base\lua\Timer.lua:228: attempt to index local 'ev' (a number value)
Stack traceback:
    File C:\TerraME\bin/lua/terrame.lua, line 1566, in function __index
    File C:\TerraME\bin\packages\base\lua\Timer.lua, line 228, in function run
    File continuous-rain.lua, line 51, in main chunk
    Internal C file, in function dofile
    File C:\TerraME\bin/lua/terrame.lua, line 1517, in main chunk
    Internal C file, in function xpcall
    File C:\TerraME\bin/lua/terrame.lua, line 1539, in function myxpcall
    File C:\TerraME\bin/lua/terrame.lua, line 1517, in main chunk

**Comment by pedro-andrade-inpe** [comment]
This error is related to the `table.insert` call in `Timer:add()`. This function was overwritten by https://github.com/TerraME/terrame/commit/fead4c3d2b541e9479ef74682cc6ecbaf7b1aa6f, but the new implementation only gets two arguments. In fact, it can get three arguments with the position in the second and the value in the third. That's why the event is being replaced by a position (number), in the error above.
