### ISSUE TITLE
verify SRID while adding a Layer to a Project

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1104]
Verify if TerraLib can find a SRID while adding a Layer to a Project. If not, show a warning pointing out that the projection should be one of the available in `.../terrame/bin/share/terralib/json/srs.json` (note that the message is different for Mac and Windows. Add an alternative test.

**Comment by pedro-andrade-inpe** [comment]
If adding a Layer to a Postgis database and there is no SRID, show an error just after the warning. This solution solves #1152.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, this issue needs more investigation because even that SRID is not found it will work. The problem in #1152 is specific to tif  > postigis, it is a really bug because terralib finds the SRID, including it is available in the json file. 
So, this warning will chage the logic of the tests, because warnings turn error, this can unfeasible for beta-2.

**Comment by pedro-andrade-inpe** [comment]
Ok, possibly we can help the user with #1145. I'll move the two issues to beta-3.
