### ISSUE TITLE
Suggestion for filePath() could verify subdirectories

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#1398]
It would be interesting for #1100, because there are subdirectories in data now.

**Comment by pedro-andrade-inpe** [comment]
In fact, when one wants to read a data that is inside a directory within `data`, it is necessary to add such directory in the argument. For example, in `functional/alternative/File.lua`:

```lua
file = File(filePath("error"..s.."csv-error.csv"))
```

I think it is dangerous to search within the internal directory as it is possible to have more than one file with the same name. What is possible to do is to verify if the directory (`error` in the example above) exists and show an error related to the directory instead of saying that the file simply does not exist, as the directory might not exist because the user downloaded the package from the repository and not from github (for instance).

**Comment by pedro-andrade-inpe** [comment]
1. Directory does not exist
2. Directory exists: suggestions must refer to the files within such directory, and not `data`.
