### ISSUE TITLE
Automatic Linux binary

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1509]
Create an automatic Linux binary tar go file in the CI server every night.

**Comment by avancinirodrigo** [comment]
This job must be after daily tests on master branch. I don't suggest to use the daily tests because it creates waste (exception -doc).
It needs the current doc, so I suggest the steps in a single job:

1. build and install terralib;
1. checkout terrame master;
1. replace terrame/git/package/{pkg}/doc to the last doc generated in daily -doc (it is necessary because cmake/cpack needs to map doc files); 
1. build and install terrame (turn ON TERRAME_CREATE_INSTALLER);
1. run the cpack command: 
```
cd /.../terrame/build-cmake/build && cpack -G TGZ -C Release --config ./CPackConfig.cmake
```

**Comment by pedro-andrade-inpe** [comment]
Good job, guys! @avancinirodrigo, @raphaelrpl
