### ISSUE TITLE
Layer:export with argument proj4

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1826]
Projections can be set while exporting a `Layer` by using `epsg` number. Allow `Layer` to be exported with a projection described as a `proj4` string, when there is no `epsg` projection available.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe, there is no such feature in terralib. How would it be?

**Comment by pedro-andrade-inpe** [comment]
It should reproject according to a proj4 description, such as "+proj=longlat +lon_0=0 +a=6371007.181 +b=6371007.181 +no_defs"

**Comment by pedro-andrade-inpe** [comment]
No, it is in the case where there is no epsg associated. Should I move it to terralib-depends?

**Comment by avancinirodrigo** [comment]
I guess so.
Terralib only knows the contents of the srs.json file where there are the associations.

**Comment by avancinirodrigo** [comment]
It seems that this issue can be implemented now.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe 
Although terralib save the proj4 in the project now, it is not possible set it in its layer yet. 
But, it seems to me that this is no longer a issue, because, when terralib don't know the data projection, it can to determine the proj4 and associate it with a user defined epsg. 
So, if you export the data with the user defined epsg, it will be exported with the proj4.
TerraME already do this when the user don't set the epsg.

**Comment by pedro-andrade-inpe** [comment]
Ok, so I'll close this issue and mark as invalid. Anyway, if the user wants to export to an unusual projection it is better to do so in a GIS.
