### ISSUE TITLE
export Boost random algorithms

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#1983]
Export all stl random number algorithms to Lua.

**Comment by pedro-andrade-inpe** [comment]
They are documented at http://www.boost.org/doc/libs/1_60_0/doc/html/boost_random/reference.html#boost_random.reference.distributions.

**Comment by avancinirodrigo** [comment]
@pedro-andrade-inpe,
It is not possible export boost directly for swig.
But, I can create a wrapper for each class and so it is possible to export.
In this way, is not interesting export all class, because of the big quantity of classes.

The random classes is going to be accessed bye TerraLib() as `TerraLib().Random` or `TerraLib().NormalDistribution`, I need to know the best way to do that.

So, I need more information about each class that will be exported.

**Comment by pedro-andrade-inpe** [comment]
Use stl instead:
http://en.cppreference.com/w/cpp/numeric/random

**Comment by pedro-andrade-inpe** [comment]
STL does not generate random numbers equally in the different operational systems. Boost does.
