### ISSUE TITLE
feedback during fill attributes

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#2068]
Think about how to give a feedback for the user during fill cell as it might take a long processing time.

**Comment by avancinirodrigo** [comment]
There is a feature on terralib that allow getting the progress of a task that is registered in the terralib task manager.
Also, there is some progress viewer classes that can be used to show the task progress.
The solution was inherited the ConsoleProgressViewer class and overwrite just the method that updates the progress view.
It can be seen in SWIG LuaProgressViewer on lua/Common.i. 

This feature was added in creating cellular space and exporting layer as well because they are a slow process.
It can be used in others functions too.

The output in the terminal is showing just when is processing a function, after finished, the output is removed. It can be changed if necessary.
See it in commit below.
