### ISSUE TITLE
Is possible to compile TerraME in VS and QtLua in MinGW and they work together? 

### ISSUE THREAD

**Issue by avancinirodrigo** [TerraME/terrame#731]
The answer of this question is very important to continue update to new version of TerraLib.

**Comment by tiagogsc** [comment]
I think that there is a way. You can compile Qlua in MinGW and then use the
MinGW tool named "reimp" to generate ".lib libraries from .a files.
Finally, use the reimp-lemented libries to link with TerraME In VS.

--
Prof. Dr. Tiago Garcia de Senna Carneiro
TerraLAB - Earth System Modelling and Simulation Laboratory
Computer Science Department, UFOP - Federal University of Ouro Preto

Campus Universitário Morro do Cruzeiro, Ouro Preto - MG, Brazil, 35400-000
+55 31 3559 1692   +55 31 3559 1253
www.terralab.ufop.br   www.decom.ufop.br

2015-09-29 16:16 GMT-03:00 Rodrigo Avancini <notifications@github.com>:

**Comment by avancinirodrigo** [comment]
Ok, lets try!

**Comment by avancinirodrigo** [comment]
The trivial solution don't work. I think as terrame use qt and qtlua use too, so is not possible to have mingw and msvs qt dlls in same system.

**Comment by tiagogsc** [comment]
In the past I tried to compile terrame and qlua with the mingw version, For
this, you should prevent Qt and QLua to install MinGW. You should your use
your own MinGW to version to compile both projects. The problem could that
this may require some patches to QLua since it haven't been updated
frequently.
Anyway, this process took me weeks.

--
Prof. Dr. Tiago Garcia de Senna Carneiro
TerraLAB - Earth System Modelling and Simulation Laboratory
Computer Science Department, UFOP - Federal University of Ouro Preto

Campus Universitário Morro do Cruzeiro, Ouro Preto - MG, Brazil, 35400-000
+55 31 3559 1692   +55 31 3559 1253
www.terralab.ufop.br   www.decom.ufop.br

2015-10-01 15:55 GMT-03:00 Rodrigo Avancini <notifications@github.com>:

**Comment by avancinirodrigo** [comment]
Currently terrame is compiled from mingw not visual, but the new terralib 5 don't give support to mingw, only visual studio is supported. That is the problem!
