### ISSUE TITLE
packages with external libraries

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#954]
Allow packages to have a directory called `lib`, where external libraries can be placed. When loading a package with an external library, all files inside `lib` must be loaded. We can load them by using `package.loadlib` using the full path: "If the string specifies a fully qualified path, the function searches only that path for the module." (http://lua-users.org/wiki/LoadLibrary).

**Comment by avancinirodrigo** [comment]
I suggest a test to `base` with qtlua and qtluaextras, because both are only necessary in Lua layer, however they are in CMake.

**Comment by pedro-andrade-inpe** [comment]
Package.lua -> import

More or less:

```lua
forEachFile(pacakgeInfo(package).foder, function(file)
    -- load lib
end)
```

**Comment by avancinirodrigo** [comment]
pros and cons:

- there is a specific order to load some lib, it means, is not possible a generic solution to list the libs in a directory and load them;

- package.loadlib() works with full paths of the libs, including extensions, it means, problem with OS;

- package with /lib become the use more complex, because it depends on compilation by user on different OS.

- package with /lib loses the feature of plug and play;

- for simple libs independents it works.
