### ISSUE TITLE
CellularSpace with argument geometry

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [TerraME/terrame#956]
Add a new argument for CellularSpace, `geometry = false` (default), which indicates whether the geometry will be loaded or not. Verify if the loaded geometry is stored in the same attribute in the cells when loading from shapefile or from a postgis database. If not, they should be changed to be loaded in the same attribute to facilitate the user. Add basic and alternative tests, and update the documentation as well. Note that virtual cellular spaces cannot use such argument. We need to think about a way to document how to use such geometries.

**Comment by avancinirodrigo** [comment]
pros and cons:

- there is a specific order to load some lib, it means, is not possible a generic solution to list the libs in a directory and load them;

- package.loadlib() works with full paths of the libs, including extensions, it means, problem with OS;

- package with /lib become the use more complex, because it depends on compilation by user on different OS.

- package with /lib loses the feature of plug and play;

- for simple libs independents it works.

**Comment by avancinirodrigo** [comment]
In shape is `OGR_GEOMETRY` and in postgis is `geom`. Can be `geom` for both?

**Comment by avancinirodrigo** [comment]
Documetation is associeted to #923.

**Comment by pedro-andrade-inpe** [comment]
It seems that there is no test for this functionality. Is it right?

**Comment by avancinirodrigo** [comment]
See in https://github.com/TerraME/terrame/commit/88cd232bb8fdecdd0c3880637f63494e1f4b1726
